Docker: adding use of bootstrap file
* Closes #116

diff --git a/{{cookiecutter.project_shortname}}/scripts/bootstrap b/{{cookiecutter.project_shortname}}/scripts/bootstrap
--- a/{{cookiecutter.project_shortname}}/scripts/bootstrap
+++ b/{{cookiecutter.project_shortname}}/scripts/bootstrap
@@ -6,15 +6,29 @@ set -e
 script_path=$(dirname "$0")
 pipfile_lock_path="$script_path/../Pipfile.lock"
 
+
+function check_for_pipfilelock {
+  if [ ! -f $pipfile_lock_path ]; then
+    if [ "$flags" == "--deploy" ]; then
+      echo "Pipfile.lock' not found. Exiting"
+      exit 1
+    else
+      echo "'Pipfile.lock' not found. Generating via 'pipenv lock --dev'..."
+      pipenv lock --dev
+    fi
+  fi
+}
+
+
 # The real bootstrap script starts 20 lines below ;-)
 flags=()
 while test $# -gt 0; do
     case "$1" in
         # If you need to add special flags to this script, this is the place:
-        # --ci)
-        #     flags=("--dev")
+         --ci)
+             flags=("--deploy")
         #     shift
-        #     ;;
+             ;;
         *)
             # Use the flags that are passed to the script directly to sync
             flags+=("$1")
@@ -22,22 +36,30 @@ while test $# -gt 0; do
             ;;
     esac
 done
+
+
+# If no flag was passed to boostrap script, set to dev env.
 if [ ${#flags[0]} -eq 0 ]; then
     flags=("--dev")
 fi
 
-
-if [ ! -f $pipfile_lock_path ]; then
-    echo "'Pipfile.lock' not found. Generating via 'pipenv lock --dev'..."
-    pipenv lock --dev
+if [ "$flags" == "--dev" ]; then
+  check_for_pipfilelock
+  pipenv sync --dev
+  # Install application code and entrypoints from 'setup.py'
+  pipenv run pip install $script_path/..
+  # Build assets
+  pipenv run invenio collect -v
+  pipenv run invenio webpack buildall
+elif [ "$flags" == "--deploy" ]; then
+  check_for_pipfilelock
+  pipenv install --system --deploy
+  # Install application code and entrypoints from 'setup.py'
+  pip install $script_path/..
+  # Build assets
+  invenio collect -v
+  invenio webpack create
+  invenio webpack install --unsafe
+  invenio webpack build
 fi
-
-# Intall locked dependencies
-pipenv sync ${flags[@]}
-# Install application code and entrypoints from 'setup.py'
-pipenv run pip install -e $script_path/..
-
-# Build assets
-pipenv run invenio collect -v
-pipenv run invenio webpack buildall
 {% endraw %}
